"""The keyterm list, taken from the words the user actually used.

The fixture is a Claude transcript in the shape Claude really writes them, with
the terms at the frequencies they were measured at across 562 real messages:

    pr(81) test(38) issue(34) draft(33) stage(23) fix(15) lambda(14) repo(13)
    feature(13) merge(12) testear(11) queries(9) deployment(9) mergear(9)
"""

from __future__ import annotations

import asyncio
import json

from voiceloop import spoken, vocabulary

MEASURED = {
    "pr": 81,
    "test": 38,
    "issue": 34,
    "draft": 33,
    "stage": 23,
    "fix": 15,
    "lambda": 14,
    "repo": 13,
    "feature": 13,
    "merge": 12,
    "testear": 11,
    "queries": 9,
    "deployment": 9,
    "mergear": 9,
    "mergeado": 5,
}


def line(role: str, content, **extra) -> str:
    entry = {"type": role, "message": {"role": role, "content": content}}
    entry.update(extra)
    return json.dumps(entry, ensure_ascii=False)


def transcript(tmp_path, name: str = "session", messages=None) -> str:
    """One `.jsonl` with the measured terms at the measured frequencies."""
    lines = []
    for term, seen in MEASURED.items():
        for index in range(seen):
            lines.append(
                line("user", f"revisá el {term} de nuevo, que quedó {index}")
            )
    # The other side of the conversation, which is not how the user speaks.
    lines.append(
        line("assistant", [{"type": "text", "text": "kubernetes " * 200}])
    )
    for extra in messages or []:
        lines.append(extra)
    path = tmp_path / f"{name}.jsonl"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


# --- what it extracts ------------------------------------------------------


def test_the_measured_vocabulary_comes_out_of_the_measured_transcripts(tmp_path):
    terms = vocabulary.extract([transcript(tmp_path)])

    for term in MEASURED:
        assert term in terms, term


def test_the_most_used_terms_come_first(tmp_path):
    terms = vocabulary.extract([transcript(tmp_path)])

    assert terms[:4] == ["pr", "test", "issue", "draft"]


def test_only_your_own_side_of_the_conversation_counts(tmp_path):
    """The assistant's turns are a hundred times the volume and none of it is you."""
    terms = vocabulary.extract([transcript(tmp_path)])

    assert "kubernetes" not in terms


def test_ordinary_spanish_is_not_vocabulary(tmp_path):
    terms = vocabulary.extract([transcript(tmp_path)])

    for word in ("que", "de", "nuevo", "revisa", "quedo"):
        assert word not in terms


def test_a_word_said_twice_is_a_typo_not_a_term(tmp_path):
    path = tmp_path / "few.jsonl"
    path.write_text(
        "\n".join(line("user", "arreglá el flargle") for _ in range(2)) + "\n",
        encoding="utf-8",
    )

    assert vocabulary.extract([path], min_count=3) == []
    assert "flargle" in vocabulary.extract([path], min_count=2)


def test_the_list_is_capped(tmp_path):
    assert len(vocabulary.extract([transcript(tmp_path)], min_count=1, limit=5)) == 5


# --- and what it refuses to read -------------------------------------------


def test_slash_command_envelopes_are_not_things_you_said(tmp_path):
    path = tmp_path / "commands.jsonl"
    path.write_text(
        "\n".join(
            [
                line("user", "<command-name>/pr-ready</command-name>"),
                line("user", "<local-command-stdout>frobnicator</local-command-stdout>"),
                line("user", "Caveat: The messages below were generated by frobnicator"),
            ]
            * 5
        )
        + "\n",
        encoding="utf-8",
    )

    assert vocabulary.extract([path], min_count=1) == []


def test_subagent_turns_are_not_things_you_said(tmp_path):
    path = tmp_path / "side.jsonl"
    path.write_text(
        "\n".join(line("user", "frobnicator", isSidechain=True) for _ in range(5)) + "\n",
        encoding="utf-8",
    )

    assert vocabulary.extract([path], min_count=1) == []


def test_tool_results_are_not_things_you_said(tmp_path):
    path = tmp_path / "tools.jsonl"
    path.write_text(
        "\n".join(
            line("user", [{"type": "tool_result", "content": "frobnicator"}])
            for _ in range(5)
        )
        + "\n",
        encoding="utf-8",
    )

    assert vocabulary.extract([path], min_count=1) == []


def test_a_transcript_that_is_not_json_is_skipped_not_fatal(tmp_path):
    path = tmp_path / "broken.jsonl"
    path.write_text("{not json\n\n" + line("user", "lambda lambda lambda") + "\n")

    assert vocabulary.extract([path], min_count=1) == ["lambda"]


def test_a_file_that_is_not_there_reads_as_nothing(tmp_path):
    assert vocabulary.extract([tmp_path / "gone.jsonl"]) == []


# --- storing it ------------------------------------------------------------


def test_what_was_extracted_survives_a_restart(tmp_path):
    vocabulary.save(tmp_path, ["mergeado", "lambda"], now=1000.0)

    assert vocabulary.load(tmp_path) == ["mergeado", "lambda"]
    assert vocabulary.age_seconds(tmp_path, now=1600.0) == 600.0


def test_never_having_been_computed_is_infinitely_old(tmp_path):
    assert vocabulary.load(tmp_path) == []
    assert vocabulary.age_seconds(tmp_path, now=1000.0) == float("inf")


def test_a_corrupt_store_is_no_store(tmp_path):
    vocabulary.store_path(tmp_path).write_text("{oops", encoding="utf-8")

    assert vocabulary.load(tmp_path) == []
    assert vocabulary.age_seconds(tmp_path, now=1.0) == float("inf")


def test_refresh_walks_the_transcripts_and_writes_the_answer(tmp_path):
    projects = tmp_path / "projects" / "a-project"
    projects.mkdir(parents=True)
    transcript(projects, "one")
    state = tmp_path / "state"

    terms = vocabulary.refresh(
        state, now=5.0, pattern=str(tmp_path / "projects" / "*" / "*.jsonl")
    )

    assert "mergeado" in terms
    assert vocabulary.load(state) == terms


def test_a_glob_that_matches_nothing_is_not_an_error(tmp_path):
    assert vocabulary.transcript_paths(str(tmp_path / "nope" / "*.jsonl")) == []


# --- and what the daemon does with it --------------------------------------


def test_the_extracted_vocabulary_reaches_the_recognizer(build, tmp_path):
    daemon = build([])
    vocabulary.save(daemon.state_dir, ["mergeado", "deployment"], now=1000.0)

    terms = daemon.keyterms()

    assert "mergeado" in terms
    assert "deployment" in terms
    # And the hand-kept list is still there, and so are the live windows.
    assert "rate-limiter" in terms
    assert "indice" in terms


def test_the_model_names_do_not_depend_on_the_extraction_at_all(build):
    """They are said, not typed, so no count of typed words will ever rank them.

    `opus` was said five times in the whole history against a cutoff of nine
    hundred — rank 6735 of a list that keeps eighty — which is why `opus 4.8`
    came back as `opu cuatro punto ocho`. Pinned, and pinned outside the
    extraction, so turning the extraction off does not take them with it.
    """
    daemon = build([])
    daemon.vocabulary_enabled = False

    terms = daemon.keyterms()

    for name in spoken.MODEL_NAMES:
        assert name in terms


def test_a_name_you_gave_a_window_is_vocabulary_too(build):
    daemon = build([])
    daemon.store.set_alias("session-1", "el del índice")

    assert "el del índice" in daemon.keyterms()


def test_the_refresh_only_runs_when_the_list_is_stale(build, tmp_path):
    daemon = build([])
    daemon.vocabulary_pattern = str(tmp_path / "projects" / "*" / "*.jsonl")
    projects = tmp_path / "projects" / "a"
    projects.mkdir(parents=True)
    transcript(projects, "one")

    assert "pr" in asyncio.run(daemon.refresh_vocabulary())
    # Fresh now, so nothing is recomputed until it ages out.
    assert asyncio.run(daemon.refresh_vocabulary()) == []
    assert "pr" in asyncio.run(daemon.refresh_vocabulary(force=True))


def test_the_refresh_can_be_turned_off_entirely(build):
    daemon = build([])
    daemon.vocabulary_enabled = False

    assert asyncio.run(daemon.refresh_vocabulary(force=True)) == []
