"""Christening a window out loud: the offer, the answer, and never asking twice.

Claude calls an unnamed window `darwin-21`. Three of those in one repo are three
identical noises, so the first time such a window announces itself voice-loop
proposes a name — from the same request that produced the summary — and takes
one answer for it before handing the microphone to the window's own question.
"""

from __future__ import annotations

import asyncio
import json

import pytest

from voiceloop.audio import AudioUnavailable
from voiceloop.daemon import Daemon
from voiceloop.events import Event
from voiceloop.milestones import MilestoneWatcher
from voiceloop.store import Store
from voiceloop.stt.mock import MockStt
from voiceloop.summarize import Summarizer, Summary

from conftest import FakeSpeaker, write_roster
from test_reply_cycle import TTY, RecordingDelivery, StubRecorder

SLUG = "tests event processor"
SUMMARY = "terminó los tests del event processor"


class NamingSummarizer(Summarizer):
    """Answers both shapes of request without going near the network."""

    def __init__(self, summary: str = SUMMARY, slug: str = SLUG):
        super().__init__(api_key="sk-test")
        self.summary = summary
        self.slug = slug
        self.calls: list[tuple[str, str]] = []

    def _call(self, text: str) -> str:
        self.calls.append(("plain", text))
        return self.summary

    def _call_named(self, text: str) -> Summary:
        self.calls.append(("named", text))
        return Summary(text=self.summary, slug=self.slug)


@pytest.fixture
def build(config, tmp_path):
    roster = tmp_path / "sessions"
    roster.mkdir()
    made: list[Daemon] = []

    def factory(replies, *, name="darwin-21", cwd="/tmp/projects/darwin", **kwargs):
        write_roster(roster, sessionId="s1", name=name, cwd=cwd, kind="interactive")
        subject = Daemon(
            config,
            store=Store(tmp_path / f"queue{len(made)}.db"),
            speaker=FakeSpeaker(),
            summarizer=kwargs.pop("summarizer", None) or NamingSummarizer(),
            watcher=MilestoneWatcher(),
            roster_dir=roster,
            recorder=kwargs.pop("recorder", None) or StubRecorder(),
            stt=MockStt(replies=list(replies), confidence=0.99),
            delivery=RecordingDelivery(),
            **kwargs,
        )
        subject.roster_path = roster
        made.append(subject)
        return subject

    try:
        yield factory
    finally:
        for subject in made:
            subject.store.close()


def transcript(tmp_path, name: str, tail: str = "Pasaron los tests. ¿Lo mergeo?") -> str:
    path = tmp_path / f"{name}.jsonl"
    path.write_text(
        json.dumps(
            {
                "type": "assistant",
                "isSidechain": False,
                "message": {"role": "assistant", "content": [{"type": "text", "text": tail}]},
            }
        )
        + "\n",
        encoding="utf-8",
    )
    return str(path)


def queue_stop(daemon: Daemon, tmp_path, *, session="s1", name="t") -> str:
    event = Event.new(
        "stop", session, tty=TTY, transcript_path=transcript(tmp_path, name), payload={}
    )
    daemon.store.ingest(event)
    return event.id


def announce(daemon: Daemon) -> None:
    asyncio.run(daemon.announce_next())


def block_again(daemon: Daemon, tmp_path, name: str = "b") -> None:
    """The same window blocks a second time — a supersede, put back in the queue.

    Superseding is what really happens (one open item per session, summary
    dropped because it describes a turn that is no longer the last one); the
    requeue stands in for the announce loop reaching it again.
    """
    daemon.store.ingest(
        Event.new("stop", "s1", tty=TTY, transcript_path=transcript(tmp_path, name))
    )
    daemon.store.requeue(daemon.store.pendings()[0].id)
    announce(daemon)


# --- when the offer is made ------------------------------------------------


def test_an_autogenerated_window_is_offered_a_name(build, tmp_path):
    daemon = build(["dale"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.speaker.texts[0].endswith("¿La llamo tests event processor?")


def test_the_offer_rides_the_summary_call_rather_than_a_second_one(build, tmp_path):
    daemon = build(["dale"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert [kind for kind, _ in daemon.summarizer.calls] == ["named"]


def test_a_window_you_named_yourself_is_never_second_guessed(build, tmp_path):
    """A name in Claude's prompt box is the name; nothing here improves on it."""
    daemon = build(["dale"], name="index-migration")
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert "¿La llamo" not in daemon.speaker.texts[0]
    assert [kind for kind, _ in daemon.summarizer.calls] == ["plain"]
    assert daemon.store.alias_asked("s1") is False


def test_busy_mode_does_not_offer_a_name_it_cannot_hear_the_answer_to(build, tmp_path):
    daemon = build([])
    daemon.busy = True
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.recorder.takes == 0
    assert daemon.store.alias_asked("s1") is False


def test_no_slug_means_no_offer(build, tmp_path):
    """A degraded summariser loses the name and keeps the announcement."""
    daemon = build([], summarizer=NamingSummarizer(slug=""))
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert "¿La llamo" not in daemon.speaker.texts[0]


# --- answering the offer ---------------------------------------------------


def test_dale_saves_the_proposed_name(build, tmp_path):
    daemon = build(["dale", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == SLUG
    assert any("Listo, tests event processor." in said for said in daemon.speaker.spoken)


def test_a_name_you_dictate_wins_over_the_one_offered(build, tmp_path):
    daemon = build(["mejor, índice de migración", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == "indice de migracion"


def test_a_confirmed_name_is_what_the_next_announcement_says(build, tmp_path):
    daemon = build(["dale", "mergealo"])
    queue_stop(daemon, tmp_path)
    announce(daemon)

    block_again(daemon, tmp_path)

    assert daemon.speaker.texts[-1].startswith("tests event processor:")


def test_a_confirmed_name_becomes_vocabulary_for_the_recognizer(build, tmp_path):
    """Saying the name of a window only works if the recognizer knows it exists."""
    daemon = build(["dale", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert SLUG in daemon.keyterms()
    assert SLUG in daemon.stt.calls[-1][1]


# --- turning it down -------------------------------------------------------


def test_no_is_remembered_so_the_offer_is_never_repeated(build, tmp_path):
    """Being asked at every announcement is worse than the autogenerated name."""
    daemon = build(["no", "mergealo"])
    queue_stop(daemon, tmp_path)
    announce(daemon)

    assert daemon.store.get_alias("s1") is None
    assert daemon.store.alias_asked("s1") is True

    daemon.stt.replies = ["mergealo"]
    block_again(daemon, tmp_path)

    assert "¿La llamo" not in daemon.speaker.texts[-1]


def test_saying_no_to_the_name_does_not_abandon_the_window(build, tmp_path):
    daemon = build(["no", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.delivery.sent == [("text", TTY, "mergealo")]


def test_silence_declines_without_burning_a_second_take(build, tmp_path):
    """Nobody is there: opening the mic again to hear the same nothing is rude."""
    daemon = build([""])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.recorder.takes == 1
    assert daemon.store.alias_asked("s1") is True
    assert daemon.store.get_alias("s1") is None


def test_an_answer_for_the_window_is_not_stored_as_a_name(build, tmp_path):
    """The mic is open on a window that is *also* waiting: sentences go through."""
    daemon = build(["mergealo cuando pasen los tests"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") is None
    assert daemon.delivery.sent == [("text", TTY, "mergealo cuando pasen los tests")]
    assert daemon.recorder.takes == 1


def test_a_microphone_that_failed_leaves_the_offer_open_for_next_time(build, tmp_path):
    """A mic that never opened is not an answer, and must not count as one."""
    daemon = build([], recorder=StubRecorder(error=AudioUnavailable("no device")))
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.alias_asked("s1") is False


def test_no_recognizer_means_no_question_nobody_could_answer(build, tmp_path):
    daemon = build([])
    daemon.stt = None
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert "¿La llamo" not in daemon.speaker.texts[0]
    assert daemon.store.alias_asked("s1") is False
