"""Christening a window out loud: the offer, the answer, and never asking twice.

Claude calls an unnamed window `darwin-21`. Three of those in one repo are three
identical noises, so the first time such a window announces itself voice-loop
proposes a name — from the same request that produced the summary — and takes
one answer for it before handing the microphone to the window's own question.
"""

from __future__ import annotations

import asyncio
import json

import pytest

from voiceloop.audio import AudioUnavailable
from voiceloop.daemon import Daemon
from voiceloop.events import Event
from voiceloop.milestones import MilestoneWatcher
from voiceloop.store import Store
from voiceloop.stt.mock import MockStt
from voiceloop.summarize import Summarizer, Summary

from conftest import FakeSpeaker, write_roster
from test_reply_cycle import TTY, RecordingDelivery, StubRecorder

SLUG = "tests event processor"
SUMMARY = "terminó los tests del event processor"


class NamingSummarizer(Summarizer):
    """Answers both shapes of request without going near the network."""

    def __init__(self, summary: str = SUMMARY, slug: str = SLUG):
        super().__init__(api_key="sk-test")
        self.summary = summary
        self.slug = slug
        self.calls: list[tuple[str, str]] = []

    def _call(self, text: str) -> str:
        self.calls.append(("plain", text))
        return self.summary

    def _call_named(self, text: str) -> Summary:
        self.calls.append(("named", text))
        return Summary(text=self.summary, slug=self.slug)


@pytest.fixture
def build(config, tmp_path):
    roster = tmp_path / "sessions"
    roster.mkdir()
    made: list[Daemon] = []

    def factory(
        replies, *, name="darwin-21", cwd="/tmp/projects/darwin", heads_up="dámelo", **kwargs
    ):
        write_roster(roster, sessionId="s1", name=name, cwd=cwd, kind="interactive")
        subject = Daemon(
            config,
            store=Store(tmp_path / f"queue{len(made)}.db"),
            speaker=FakeSpeaker(),
            summarizer=kwargs.pop("summarizer", None) or NamingSummarizer(),
            watcher=MilestoneWatcher(),
            roster_dir=roster,
            recorder=kwargs.pop("recorder", None) or StubRecorder(),
            # An announcement is a heads-up now — a name and a four-second mic.
            # Everything below is about what happens *after* "dámelo", so the
            # word that asks for it is prepended once, here.
            stt=MockStt(
                replies=([heads_up] if heads_up else []) + list(replies), confidence=0.99
            ),
            delivery=RecordingDelivery(),
            **kwargs,
        )
        subject.roster_path = roster
        made.append(subject)
        return subject

    try:
        yield factory
    finally:
        for subject in made:
            subject.store.close()


def transcript(tmp_path, name: str, tail: str = "Pasaron los tests. ¿Lo mergeo?") -> str:
    path = tmp_path / f"{name}.jsonl"
    path.write_text(
        json.dumps(
            {
                "type": "assistant",
                "isSidechain": False,
                "message": {"role": "assistant", "content": [{"type": "text", "text": tail}]},
            }
        )
        + "\n",
        encoding="utf-8",
    )
    return str(path)


def queue_stop(daemon: Daemon, tmp_path, *, session="s1", name="t") -> str:
    event = Event.new(
        "stop", session, tty=TTY, transcript_path=transcript(tmp_path, name), payload={}
    )
    daemon.store.ingest(event)
    return event.id


def announce(daemon: Daemon) -> None:
    asyncio.run(daemon.announce_next())


def block_again(daemon: Daemon, tmp_path, name: str = "b", *, then=("mergealo",)) -> None:
    """The same window blocks a second time — a supersede, put back in the queue.

    Superseding is what really happens (one open item per session, summary
    dropped because it describes a turn that is no longer the last one); the
    requeue stands in for the announce loop reaching it again.
    """
    daemon.store.ingest(
        Event.new("stop", "s1", tty=TTY, transcript_path=transcript(tmp_path, name))
    )
    daemon.store.requeue(daemon.store.pendings()[0].id)
    daemon.stt.replies = ["dámelo", *then]
    announce(daemon)


# --- when the offer is made ------------------------------------------------


def test_an_autogenerated_window_is_offered_a_name(build, tmp_path):
    daemon = build(["dale"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.speaker.spoken[0].endswith("¿La llamo tests event processor?")


def test_the_offer_rides_the_summary_call_rather_than_a_second_one(build, tmp_path):
    daemon = build(["dale"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert [kind for kind, _ in daemon.summarizer.calls] == ["named"]


def test_a_window_you_named_yourself_is_never_second_guessed(build, tmp_path):
    """A name in Claude's prompt box is the name; nothing here improves on it."""
    daemon = build(["dale"], name="index-migration")
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert not any("¿La llamo" in said for said in daemon.speaker.spoken)
    assert [kind for kind, _ in daemon.summarizer.calls] == ["plain"]
    assert daemon.store.alias_asked("s1") is False


def test_busy_mode_does_not_offer_a_name_it_cannot_hear_the_answer_to(build, tmp_path):
    daemon = build([])
    daemon.busy = True
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.recorder.takes == 0
    assert daemon.store.alias_asked("s1") is False


def test_no_slug_means_no_offer(build, tmp_path):
    """A degraded summariser loses the name and keeps the announcement."""
    daemon = build([], summarizer=NamingSummarizer(slug=""))
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert not any("¿La llamo" in said for said in daemon.speaker.spoken)


# --- answering the offer ---------------------------------------------------


def test_dale_saves_the_proposed_name(build, tmp_path):
    daemon = build(["dale", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == SLUG
    assert any("Listo, tests event processor." in said for said in daemon.speaker.spoken)


def test_a_yes_that_repeats_the_name_back_is_still_a_yes(build, tmp_path):
    """The first real run: the offer was accepted and the acceptance was typed.

    "sí llama la fecha actual" (verbatim from the log) is five words, so the
    length rule read it as a sentence, declined the name, and delivered the
    acceptance into the window it was accepting for.
    """
    daemon = build(
        ["sí llama la fecha actual", "mergealo"],
        summarizer=NamingSummarizer(slug="fecha actual"),
    )
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == "fecha actual"
    assert daemon.delivery.sent == [("text", TTY, "mergealo")]


def test_a_yes_carrying_a_different_name_uses_that_one(build, tmp_path):
    daemon = build(["dale, llamala índice de migración", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == "indice de migracion"


def test_a_yes_with_a_sentence_after_it_names_and_answers_the_window(build, tmp_path):
    """Nothing anybody said is thrown away: the yes names, the rest goes through."""
    daemon = build(["dale, mergealo cuando pasen los tests"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == SLUG
    assert daemon.delivery.sent == [("text", TTY, "mergealo cuando pasen los tests")]


# --- the one band that is genuinely doubtful --------------------------------

DOUBT = "¿Es el nombre, o te lo mando a la ventana?"


def asked_which(daemon) -> bool:
    return any(DOUBT in said for said in daemon.speaker.spoken)


def test_a_yes_and_a_short_phrase_is_asked_about_rather_than_guessed(build, tmp_path):
    """"dale, mergealo" is a name and an answer in equal measure. Ask."""
    daemon = build(["dale, mergealo", "el nombre"])
    daemon.stt.default = ""
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert asked_which(daemon)
    assert daemon.store.get_alias("s1") == "mergealo"
    assert daemon.delivery.sent == []


def test_and_it_goes_to_the_window_when_that_is_what_it_was(build, tmp_path):
    daemon = build(["dale, mergealo", "a la ventana"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == SLUG  # the yes was real
    assert daemon.delivery.sent == [("text", TTY, "mergealo")]


def test_a_bare_yes_to_the_doubt_takes_the_half_it_was_asked_first(build, tmp_path):
    daemon = build(["dale, mergealo", "sí"])
    daemon.stt.default = ""
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == "mergealo"


def test_a_bare_no_to_the_doubt_sends_it_to_the_window(build, tmp_path):
    daemon = build(["dale, mergealo", "no"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == SLUG
    assert daemon.delivery.sent == [("text", TTY, "mergealo")]


def test_saying_something_else_replaces_it_the_way_any_read_back_does(build, tmp_path):
    daemon = build(["dale, mergealo", "mejor corré los tests primero"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == SLUG
    assert daemon.delivery.sent == [("text", TTY, "mejor corré los tests primero")]


def test_nobody_answering_the_doubt_types_nothing_anywhere(build, tmp_path):
    daemon = build(["dale, mergealo", ""])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == SLUG
    assert daemon.delivery.sent == []


def test_a_mic_that_dies_mid_doubt_leaves_the_offer_for_next_time(build, tmp_path):
    class DyingRecorder(StubRecorder):
        dies_after = 2  # the heads-up, the offer, and then the doubt

        async def record(self, destination, *, stop=None, on_open=None, speech_timeout=None):
            if self.takes >= self.dies_after:
                self.error = AudioUnavailable("no device")
            return await super().record(
                destination, stop=stop, on_open=on_open, speech_timeout=speech_timeout
            )

    daemon = build(["dale, mergealo"], recorder=DyingRecorder())
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") is None
    assert daemon.delivery.sent == []


# --- and the four that are not doubtful at all ------------------------------


def test_a_bare_yes_is_never_asked_about(build, tmp_path):
    daemon = build(["dale", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert asked_which(daemon) is False
    assert daemon.store.get_alias("s1") == SLUG


def test_a_yes_repeating_the_offered_name_is_never_asked_about(build, tmp_path):
    """Verbatim from the log, and verified by hand: agreement, not news."""
    daemon = build(
        ["sí llama la fecha actual", "mergealo"],
        summarizer=NamingSummarizer(slug="fecha actual"),
    )
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert asked_which(daemon) is False
    assert daemon.store.get_alias("s1") == "fecha actual"


def test_a_phrase_that_says_it_is_a_name_is_never_asked_about(build, tmp_path):
    daemon = build(["dale, llamala índice de migración", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert asked_which(daemon) is False
    assert daemon.store.get_alias("s1") == "indice de migracion"


def test_a_yes_and_a_whole_sentence_is_never_asked_about(build, tmp_path):
    daemon = build(["dale, mergealo cuando pasen los tests"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert asked_which(daemon) is False
    assert daemon.store.get_alias("s1") == SLUG
    assert daemon.delivery.sent == [("text", TTY, "mergealo cuando pasen los tests")]


def test_no_and_silence_are_never_asked_about(build, tmp_path):
    declined = build(["no", "mergealo"])
    queue_stop(declined, tmp_path)
    announce(declined)

    quiet = build([""])
    queue_stop(quiet, tmp_path, name="q")
    announce(quiet)

    assert asked_which(declined) is False
    assert asked_which(quiet) is False
    assert declined.store.get_alias("s1") is None
    assert quiet.store.get_alias("s1") is None


def test_a_long_phrase_with_no_yes_is_never_asked_about(build, tmp_path):
    daemon = build(["mergealo cuando pasen los tests"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert asked_which(daemon) is False
    assert daemon.delivery.sent == [("text", TTY, "mergealo cuando pasen los tests")]


def test_a_name_you_dictate_wins_over_the_one_offered(build, tmp_path):
    daemon = build(["mejor, índice de migración", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") == "indice de migracion"


def test_a_confirmed_name_is_what_the_next_announcement_says(build, tmp_path):
    daemon = build(["dale", "mergealo"])
    queue_stop(daemon, tmp_path)
    announce(daemon)

    block_again(daemon, tmp_path)

    assert daemon.speaker.texts[-1] == "Nuevo evento de tests event processor."


def test_a_confirmed_name_becomes_vocabulary_for_the_recognizer(build, tmp_path):
    """Saying the name of a window only works if the recognizer knows it exists."""
    daemon = build(["dale", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert SLUG in daemon.keyterms()
    assert SLUG in daemon.stt.calls[-1][1]


# --- turning it down -------------------------------------------------------


def test_no_is_remembered_so_the_offer_is_never_repeated(build, tmp_path):
    """Being asked at every announcement is worse than the autogenerated name."""
    daemon = build(["no", "mergealo"])
    queue_stop(daemon, tmp_path)
    announce(daemon)

    assert daemon.store.get_alias("s1") is None
    assert daemon.store.alias_asked("s1") is True
    already_said = len(daemon.speaker.spoken)

    block_again(daemon, tmp_path)

    assert not any("¿La llamo" in said for said in daemon.speaker.spoken[already_said:])


def test_saying_no_to_the_name_does_not_abandon_the_window(build, tmp_path):
    daemon = build(["no", "mergealo"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.delivery.sent == [("text", TTY, "mergealo")]


def test_silence_declines_without_burning_a_second_take(build, tmp_path):
    """Nobody is there: opening the mic again to hear the same nothing is rude."""
    daemon = build([""])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.recorder.takes == 2  # the heads-up, then the offer
    assert daemon.store.alias_asked("s1") is True
    assert daemon.store.get_alias("s1") is None


def test_an_answer_for_the_window_is_not_stored_as_a_name(build, tmp_path):
    """The mic is open on a window that is *also* waiting: sentences go through."""
    daemon = build(["mergealo cuando pasen los tests"])
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.get_alias("s1") is None
    assert daemon.delivery.sent == [("text", TTY, "mergealo cuando pasen los tests")]
    assert daemon.recorder.takes == 2


def test_a_microphone_that_failed_leaves_the_offer_open_for_next_time(build, tmp_path):
    """A mic that never opened is not an answer, and must not count as one."""
    daemon = build([], recorder=StubRecorder(error=AudioUnavailable("no device")))
    queue_stop(daemon, tmp_path)

    announce(daemon)

    assert daemon.store.alias_asked("s1") is False


def test_no_recognizer_means_no_question_nobody_could_answer(build, tmp_path):
    daemon = build([])
    daemon.stt = None
    queue_stop(daemon, tmp_path)

    announce(daemon)

    # The summary still comes — there is no "dámelo" to ask with — but nothing
    # is asked, because there would be no way to answer it.
    assert daemon.speaker.spoken == [SUMMARY + "."]
    assert daemon.store.alias_asked("s1") is False
