from __future__ import annotations

import json
import os

import pytest

from voiceloop import roster
from voiceloop.roster import Session

from conftest import write_roster

DEAD_PID = 999_999_999


def session(**overrides) -> Session:
    fields = {
        "pid": os.getpid(),
        "session_id": "session-1",
        "cwd": "/tmp/projects/workspace",
        "kind": "interactive",
        "name": "workspace-21",
        "status": "idle",
    }
    fields.update(overrides)
    return Session(**fields)


# --- the auto-generated-name test ----------------------------------------


@pytest.mark.parametrize("name", ["workspace-21", "workspace-ae", "workspace-7b", "workspace-f2"])
def test_claude_generated_names_are_detected(name):
    """`<cwd basename>-<2 hex>` is what Claude picks when you don't name a window."""
    assert session(name=name).has_autogenerated_name is True
    assert session(name=name).announce_name is None


@pytest.mark.parametrize(
    "name",
    [
        "draft-mode-changes",
        "sidepanel-test",
        "workspace-migration",
        "workspace-2",
        "workspace-211",
        "workspace-zz",
        "workspace-AE-2",
        "workspace",
        "",
    ],
)
def test_user_chosen_names_are_kept(name):
    assert session(name=name).has_autogenerated_name is False


def test_uppercase_hex_still_counts_as_auto_generated():
    assert session(name="workspace-AE").has_autogenerated_name is True


def test_a_prefix_that_is_not_the_cwd_basename_is_a_real_name():
    assert session(cwd="/tmp/projects/other", name="workspace-21").has_autogenerated_name is False


def test_a_trailing_slash_in_cwd_does_not_break_the_match():
    assert session(cwd="/tmp/projects/workspace/", name="workspace-21").has_autogenerated_name


def test_no_cwd_means_we_cannot_tell_so_the_name_is_used():
    assert session(cwd="", name="workspace-21").has_autogenerated_name is False


def test_a_user_chosen_name_is_the_one_announced():
    assert session(name="draft-mode-changes").announce_name == "draft-mode-changes"


# --- liveness -------------------------------------------------------------


def test_the_current_process_is_alive():
    assert roster.pid_alive(os.getpid()) is True


@pytest.mark.parametrize("pid", [DEAD_PID, 0, -1, None, "1234"])
def test_bad_or_dead_pids_are_not_alive(pid):
    assert roster.pid_alive(pid) is False


# --- loading --------------------------------------------------------------


def test_sessions_are_keyed_by_session_id(tmp_path):
    write_roster(tmp_path, sessionId="alpha", name="one")
    write_roster(tmp_path, sessionId="beta", name="two")

    loaded = roster.load(tmp_path)

    assert set(loaded) == {"alpha", "beta"}
    assert loaded["alpha"].name == "one"


def test_dead_sessions_are_dropped(tmp_path):
    write_roster(tmp_path, sessionId="alive")
    write_roster(tmp_path, sessionId="dead", pid=DEAD_PID)

    assert set(roster.load(tmp_path)) == {"alive"}
    assert set(roster.load(tmp_path, require_alive=False)) == {"alive", "dead"}


def test_background_agents_can_be_filtered_out(tmp_path):
    write_roster(tmp_path, sessionId="ui", kind="interactive")
    write_roster(tmp_path, sessionId="agent", kind="bg", name="Some background task")

    everything = roster.load(tmp_path)
    interactive = roster.load(tmp_path, interactive_only=True)

    assert set(everything) == {"ui", "agent"}
    assert set(interactive) == {"ui"}
    assert everything["agent"].is_interactive is False


def test_find_returns_one_session_or_none(tmp_path):
    write_roster(tmp_path, sessionId="alpha")

    assert roster.find("alpha", tmp_path).session_id == "alpha"
    assert roster.find("nope", tmp_path) is None
    assert roster.find("", tmp_path) is None


def test_a_corrupt_roster_file_is_skipped(tmp_path):
    write_roster(tmp_path, sessionId="good")
    (tmp_path / "broken.json").write_text("{ truncated", encoding="utf-8")
    (tmp_path / "array.json").write_text("[1,2,3]", encoding="utf-8")
    (tmp_path / "nosession.json").write_text(json.dumps({"pid": os.getpid()}), encoding="utf-8")

    assert set(roster.load(tmp_path)) == {"good"}


def test_missing_roster_directory_is_empty(tmp_path):
    assert roster.load(tmp_path / "nope") == {}
    assert list(roster.live_session_ids(tmp_path / "nope")) == []


def test_unexpected_field_types_degrade_to_empty_strings(tmp_path):
    tmp_path.mkdir(exist_ok=True)
    (tmp_path / "weird.json").write_text(
        json.dumps({"pid": os.getpid(), "sessionId": "weird", "cwd": 12, "name": None}),
        encoding="utf-8",
    )

    loaded = roster.load(tmp_path)["weird"]

    assert (loaded.cwd, loaded.name, loaded.kind) == ("", "", "")


def test_the_waiting_status_is_read_verbatim(tmp_path):
    write_roster(tmp_path, sessionId="alpha", status=roster.STATUS_WAITING)

    assert roster.load(tmp_path)["alpha"].status == "waiting"


def test_default_roster_dir_expands_the_home_tilde(monkeypatch, tmp_path):
    monkeypatch.setenv("HOME", str(tmp_path))

    assert roster.roster_dir() == tmp_path / ".claude/sessions"
