"""Claude Code's live session roster.

Claude keeps one JSON file per running session under `~/.claude/sessions/`:

    {"pid":50177,"sessionId":"…","cwd":"…","kind":"interactive",
     "name":"draft-mode-changes","status":"busy","version":"2.1.220"}

voice-loop uses it for three things: the **name** to announce (Claude's own, so
what you hear matches what you see in the prompt box), the `kind` filter that
keeps background agents out of the queue, and a best-effort reconciliation
after a daemon restart — items whose session is gone are resolved rather than
announced into the void.

`status` is *not* used as the "needs you" signal; the hooks are. `idle` also
means "finished, nothing pending", which is not the same thing.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

KIND_INTERACTIVE = "interactive"
KIND_BACKGROUND = "bg"

STATUS_WAITING = "waiting"
STATUS_BUSY = "busy"

DEFAULT_ROSTER_DIR = "~/.claude/sessions"

# Claude's auto-generated names are "<cwd basename>-<2 hex chars>" (darwin-21,
# darwin-ae). Anything else was named by the user and is worth announcing.
_AUTO_SUFFIX = re.compile(r"^[0-9a-f]{2}$")


def roster_dir(path: str | Path | None = None) -> Path:
    return Path(os.path.expanduser(str(path or DEFAULT_ROSTER_DIR)))


def pid_alive(pid: int) -> bool:
    if not isinstance(pid, int) or pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return False
    return True


@dataclass(frozen=True)
class Session:
    pid: int
    session_id: str
    cwd: str
    kind: str
    name: str
    status: str
    raw: dict = field(default_factory=dict, repr=False)

    @property
    def is_interactive(self) -> bool:
        return self.kind == KIND_INTERACTIVE

    @property
    def is_alive(self) -> bool:
        return pid_alive(self.pid)

    @property
    def has_autogenerated_name(self) -> bool:
        """True when Claude picked the name, i.e. the user never named the window."""
        if not self.name or not self.cwd:
            return False
        base = os.path.basename(self.cwd.rstrip("/"))
        if not base:
            return False
        prefix, sep, suffix = self.name.rpartition("-")
        if not sep:
            return False
        return prefix == base and bool(_AUTO_SUFFIX.match(suffix.lower()))

    @property
    def announce_name(self) -> str | None:
        """The name to speak, or None when the session is still unnamed."""
        if not self.name or self.has_autogenerated_name:
            return None
        return self.name


def _parse(path: Path) -> Session | None:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(raw, dict):
        return None
    session_id = raw.get("sessionId")
    if not isinstance(session_id, str) or not session_id:
        return None
    pid = raw.get("pid")
    return Session(
        pid=pid if isinstance(pid, int) else 0,
        session_id=session_id,
        cwd=raw.get("cwd") if isinstance(raw.get("cwd"), str) else "",
        kind=raw.get("kind") if isinstance(raw.get("kind"), str) else "",
        name=raw.get("name") if isinstance(raw.get("name"), str) else "",
        status=raw.get("status") if isinstance(raw.get("status"), str) else "",
        raw=raw,
    )


def load(
    directory: str | Path | None = None,
    *,
    require_alive: bool = True,
    interactive_only: bool = False,
) -> dict[str, Session]:
    """Every session in the roster, keyed by sessionId."""
    base = roster_dir(directory)
    sessions: dict[str, Session] = {}
    try:
        entries = sorted(base.glob("*.json"))
    except OSError:
        return {}
    for entry in entries:
        session = _parse(entry)
        if session is None:
            continue
        if require_alive and not session.is_alive:
            continue
        if interactive_only and not session.is_interactive:
            continue
        sessions[session.session_id] = session
    return sessions


def find(
    session_id: str, directory: str | Path | None = None, *, require_alive: bool = True
) -> Session | None:
    if not session_id:
        return None
    return load(directory, require_alive=require_alive).get(session_id)


def live_session_ids(directory: str | Path | None = None) -> Iterable[str]:
    return load(directory).keys()
