import Foundation
#if canImport(Darwin)
import Darwin
#endif

/// Claude Code's live session roster. Port of `roster.py`.
///
/// Claude keeps one JSON file per running session under `~/.claude/sessions/`.
/// voice-loop uses it for the name to announce (Claude's own, so what you hear
/// matches the prompt box), the `kind` filter that keeps background agents out,
/// and reconciliation after a restart.
public enum Roster {
    public static let kindInteractive = "interactive"
    public static let kindBackground = "bg"
    public static let statusWaiting = "waiting"
    public static let statusBusy = "busy"
    public static let defaultDir = "~/.claude/sessions"

    public struct Session: Equatable, Sendable {
        public let pid: Int
        public let sessionId: String
        public let cwd: String
        public let kind: String
        public let name: String
        public let status: String

        public init(pid: Int, sessionId: String, cwd: String, kind: String, name: String, status: String) {
            self.pid = pid
            self.sessionId = sessionId
            self.cwd = cwd
            self.kind = kind
            self.name = name
            self.status = status
        }

        public var isInteractive: Bool { kind == kindInteractive }
        public var isAlive: Bool { pidAlive(pid) }

        /// True when Claude picked the name: `<cwd basename>-<2 hex chars>`
        /// (darwin-21, darwin-ae). Anything else was named by the user.
        public var hasAutogeneratedName: Bool {
            if name.isEmpty || cwd.isEmpty { return false }
            let base = (cwd as NSString).lastPathComponent
            let trimmedBase = base.hasSuffix("/") ? String(base.dropLast()) : base
            if trimmedBase.isEmpty { return false }
            guard let dash = name.range(of: "-", options: .backwards) else { return false }
            let prefix = String(name[name.startIndex..<dash.lowerBound])
            let suffix = String(name[dash.upperBound...]).lowercased()
            if prefix != trimmedBase { return false }
            return suffix.count == 2 && suffix.allSatisfy { $0.isHexDigit }
        }

        /// The name to speak, or nil when the session is still unnamed.
        public var announceName: String? {
            if name.isEmpty || hasAutogeneratedName { return nil }
            return name
        }
    }

    /// `os.kill(pid, 0)`: alive if the signal would be deliverable.
    public static func pidAlive(_ pid: Int) -> Bool {
        guard pid > 0 else { return false }
        let result = kill(pid_t(pid), 0)
        if result == 0 { return true }
        return errno == EPERM
    }

    public static func directory(_ path: String? = nil) -> URL {
        URL(fileURLWithPath: NSString(string: path ?? defaultDir).expandingTildeInPath)
    }

    static func parse(_ url: URL) -> Session? {
        guard let data = try? Data(contentsOf: url),
              let raw = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any],
              let sessionId = raw["sessionId"] as? String, !sessionId.isEmpty
        else { return nil }
        let pid = raw["pid"] as? Int ?? 0
        return Session(
            pid: pid,
            sessionId: sessionId,
            cwd: raw["cwd"] as? String ?? "",
            kind: raw["kind"] as? String ?? "",
            name: raw["name"] as? String ?? "",
            status: raw["status"] as? String ?? ""
        )
    }

    /// Every session in the roster, keyed by sessionId.
    public static func load(
        _ directory: String? = nil,
        requireAlive: Bool = true,
        interactiveOnly: Bool = false
    ) -> [String: Session] {
        let base = self.directory(directory)
        guard let entries = try? FileManager.default.contentsOfDirectory(
            at: base, includingPropertiesForKeys: nil
        ) else { return [:] }
        var sessions: [String: Session] = [:]
        for entry in entries.sorted(by: { $0.path < $1.path }) where entry.pathExtension == "json" {
            guard let session = parse(entry) else { continue }
            if requireAlive && !session.isAlive { continue }
            if interactiveOnly && !session.isInteractive { continue }
            sessions[session.sessionId] = session
        }
        return sessions
    }

    public static func find(_ sessionId: String, directory: String? = nil, requireAlive: Bool = true) -> Session? {
        guard !sessionId.isEmpty else { return nil }
        return load(directory, requireAlive: requireAlive)[sessionId]
    }
}
