import XCTest
@testable import VoiceLoopCore

final class RosterTests: XCTestCase {
    func testHasAutogeneratedName() {
        let auto = Roster.Session(pid: 1, sessionId: "a", cwd: "/Users/x/Documents/darwin",
                                  kind: "interactive", name: "darwin-21", status: "busy")
        XCTAssertTrue(auto.hasAutogeneratedName)
        XCTAssertNil(auto.announceName)

        let named = Roster.Session(pid: 1, sessionId: "a", cwd: "/Users/x/Documents/darwin",
                                   kind: "interactive", name: "conflictos", status: "busy")
        XCTAssertFalse(named.hasAutogeneratedName)
        XCTAssertEqual(named.announceName, "conflictos")

        // A non-hex suffix is a user name, not autogenerated.
        let hexish = Roster.Session(pid: 1, sessionId: "a", cwd: "/Users/x/Documents/darwin",
                                    kind: "interactive", name: "darwin-zz", status: "busy")
        XCTAssertFalse(hexish.hasAutogeneratedName)
    }

    func testInteractiveKind() {
        let bg = Roster.Session(pid: 1, sessionId: "a", cwd: "/x", kind: "bg", name: "n", status: "busy")
        XCTAssertFalse(bg.isInteractive)
        let interactive = Roster.Session(pid: 1, sessionId: "a", cwd: "/x", kind: "interactive", name: "n", status: "busy")
        XCTAssertTrue(interactive.isInteractive)
    }

    func testPidAlive() {
        XCTAssertTrue(Roster.pidAlive(Int(ProcessInfo.processInfo.processIdentifier)))
        XCTAssertFalse(Roster.pidAlive(0))
        XCTAssertFalse(Roster.pidAlive(999_999))
    }

    func testLoadParsesDirectory() throws {
        let dir = NSTemporaryDirectory() + "vl-roster-\(UUID().uuidString)"
        try FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
        let pid = Int(ProcessInfo.processInfo.processIdentifier)
        let json = #"{"pid":\#(pid),"sessionId":"s1","cwd":"/x","kind":"interactive","name":"n","status":"busy"}"#
        try json.write(toFile: dir + "/s1.json", atomically: true, encoding: .utf8)
        let sessions = Roster.load(dir, requireAlive: true, interactiveOnly: true)
        XCTAssertEqual(sessions["s1"]?.name, "n")
    }
}
